### ISSUE TITLE
The name of the server in the `kubeconfig` file gets overwritten after login

### ISSUE THREAD

**Issue by bsctl** [clastix/kubectl-login#18]
After merging #17 there is an issue about the name of the server in the `kubeconfig` file gets overwritten after login. 

```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://cmp.clastix.io:9443
  name: kubernetes         # <<< here
contexts:
- context:
    cluster: kubernetes
    user: oidc
  name: oidc
current-context: oidc
kind: Config
preferences: {}
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - login
      - get-token
      command: kubectl
      env: null
      provideClusterInfo: false
```

The server is named always as `kubernetes` in the merged `kubeconfig` file. If there is another server in the current `kubeconfig` file already called `kubernetes`, it will be overwritten. What about to take the name from the `--k8s-api-server` option value? Or better, from the `kubeconfig cluster-info` API?
